version: '3.5'
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       - http_proxy
  #       - https_proxy
  #       - no_proxy
  #   image: budget-track-app/server:latest
    # ports:
    #   - '8081:8081'
  mysql:
    image: mysql:8.0.28-oracle
    ports:
      - '3307:3306'    
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql/
    environment:
      - MYSQL_USER=sudo
      # MYSQL_PORT: 3306
      # MYSQL_ALLOW_EMPTY_PASSWORD: false
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=budgetAppDB
    networks:
      - app-network
networks:
  app-network:
    driver: bridge



# volumes:
#   mysql-data:
#     driver: local